/*-DELETE DUPLICATE VALUES USING COUNT*--*/

/* I WANT TO DELETE THE DUPLICATE ROWS FIRST I WILL SEE WHICH ROW IS REPEATED*/
SELECT *, COUNT(*) FROM EMP GROUP BY NAME ;

/* NOW I WANT TO SEE WHICH ROW  IS REPEATED OR DUPLICATE */
SELECT * , COUNT(*) FROM EMP 
GROUP BY NAME 
HAVING COUNT(*) > 1 ;

/* NOW I WANT TO SEE THE ID OF THAT DUPLICATE ROW*/

SELECT ID FROM
(SELECT * , COUNT(*) FROM EMP 
GROUP BY NAME 
HAVING COUNT(*) > 1 )AS DUP;


/* NOW I WANT TO DELETE THIS ID WHICH IS REPEATED */
DELETE FROM EMP
WHERE ID IN (
SELECT ID FROM
(SELECT * , COUNT(*) FROM EMP 
GROUP BY NAME 
HAVING COUNT(*) > 1 ) AS DUP);


















