select(salary) ,emp_id,FIRST_NAME  from myemp order by salary desc;

select * from myemp ;
/*SECOND HIGHEST SALARY*/
SELECT MAX(SALARY) FROM myemp
WHERE SALARY NOT IN (SELECT MAX(SALARY) FROM MYEMP) ;



/*3RD HIGHEST SALARY*/
SELECT EMP_ID , FIRST_NAME , SALARY FROM myemp E1
 WHERE 3-1 = (SELECT COUNT(DISTINCT SALARY)
 FROM MYEMP E2 
 WHERE E2.SALARY>E1.SALARY);
 
 
 /*10TH HIGHEST SALARY*/
 SELECT DISTINCT(SALARY ), FIRST_NAME  FROM MYEMP E1
 WHERE 10-1= 
 (SELECT COUNT(DISTINCT SALARY) 
FROM MYEMP E2 
WHERE E2.SALARY>E1.SALARY) ;
















